[metadata]
name = "gruvfox"
author = "EdenEast"
origin_url = "https://github.com/EdenEast/nightfox.nvim"

[colors]
foreground = "#ebdbb2"
background = "#282828"
cursor_bg = "#ebdbb2"
cursor_border = "#ebdbb2"
cursor_fg = "#282828"
compose_cursor = '#fe8019'
selection_bg = "#32302f"
selection_fg = "#ebdbb2"
scrollbar_thumb = "#bdae93"
split = "#1d2021"
visual_bell = "#ebdbb2"
ansi = ["#282828", "#fb4934", "#b8bb26", "#fabd2f", "#83a598", "#d3869b", "#8ec07c", "#fbf1c7"]
brights = ["#484848", "#fc6452", "#bfc23c", "#fbc74e", "#96b3a7", "#e0aab9", "#9fc990", "#fcf3cf"]

[colors.indexed]
16 = "#d3869b"
17 = "#fe8019"

[colors.tab_bar]
background = "#1d2021"
inactive_tab_edge = "#1d2021"
inactive_tab_edge_hover = "#3c3836"

[colors.tab_bar.active_tab]
bg_color = "#bdae93"
fg_color = "#282828"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#3c3836"
fg_color = "#d5c4a1"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#504945"
fg_color = "#ebdbb2"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#282828"
fg_color = "#d5c4a1"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#504945"
fg_color = "#ebdbb2"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

